### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by JekSun97** [GodotSteam/GodotSteam-Example-Project#3]
This is the error that comes up on startup:
res://src/global.gd:23 - Parse Error: The identifier "Steam" isn't declared in the current scope.

Godot 3.5.3

![123](https://github.com/CoaguCo-Industries/GodotSteam-Example-Project/assets/130399274/61d8cc4e-117c-40fa-8f63-2d1a28539999)

**Comment by Gramps** [comment]
Hey there!  If you see that then you aren't using an editor that has GodotSteam enabled.  You will need either one of our pre-compiled editors or the GDExtension for GodotSteam.

**Comment by JekSun97** [comment]
I downloaded the correct editor, but the example still doesn't run and throws other errors
![err2](https://github.com/CoaguCo-Industries/GodotSteam-Example-Project/assets/130399274/8508a106-eb22-4207-b891-9eb9765da0a1)

**Comment by Gramps** [comment]
You can try deleting the .import folder and then reopen it.  That folder shouldn't be there anyway so I need to remove it from the repo.

**Comment by JekSun97** [comment]
Deleting the .import folder did not help :(

**Comment by Gramps** [comment]
Oh, haha, my bad.  I was only looking at the errors.  It says in the initialization line that Steam is not running.  Steam must be running and you have to be signed in to use Steamworks.

**Comment by JekSun97** [comment]
Great, the example worked! But there are still errors in the console, I believe that projects that are launched without Steam running will also crash with an error, should it be? :D

**Comment by Gramps** [comment]
Sometimes they can, depends on the error and how severe it is.  The initialization process can also be tailored to have the game shut down or just ignore Steamworks depending on different failures.

What errors do you have now?

**Comment by JekSun97** [comment]
The same as in the last screenshot

**Comment by Gramps** [comment]
Ah, just import errors?  Closing the editor, deleting that folder, then opening the project again should have cleared those up.  Though it shouldn't really hurt anything.

**Comment by Gramps** [comment]
This issue has been open for some time!  Has anything changed?

**Comment by Gramps** [comment]
Due to the age and inactivity, I will close this for now.  If there is still an issue, please feel free to update this!
